//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreinamentoBitzen.Dados.Entidades
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class TreinamentoContext : DbContext
    {
        public TreinamentoContext()
            : base("name=TreinamentoContext")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Driver> ListDrivers { get; set; }
        public virtual DbSet<FuelType> ListFuelTypes { get; set; }
        public virtual DbSet<Manufacturer> ListManufacturers { get; set; }
        public virtual DbSet<Refuel> ListRefuels { get; set; }
        public virtual DbSet<Vehicle> ListVehicles { get; set; }

        public System.Data.Entity.DbSet<Manufacturer> Manufacturer { get; set; }
        public System.Data.Entity.DbSet<Vehicle> Vehicle { get; set; }
        public System.Data.Entity.DbSet<Driver> Driver { get; set; }
        public System.Data.Entity.DbSet<FuelType> FuelType { get; set; }
    }
}