//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreinamentoBitzen.Dados.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refuel
    {
        public int Id { get; set; }
        public int VehicleId { get; set; }
        public int FuelTypeId { get; set; }
        public int DriverId { get; set; }
        public System.DateTime RefuelDate { get; set; }
        public decimal Qty { get; set; }
        public decimal Price { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual FuelType FuelType { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
