//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreinamentoBitzen.Dados.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.ListRefuels = new HashSet<Refuel>();
        }
    
        public int Id { get; set; }
        public bool Active { get; set; }
        public string LicensePlate { get; set; }
        public string Name { get; set; }
        public int FuelTypesId { get; set; }
        public int ManufacturersId { get; set; }
        public int ManufactureYear { get; set; }
        public int TankCapacity { get; set; }
        public string Remarks { get; set; }
    
        public virtual FuelType FuelType { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refuel> ListRefuels { get; set; }
    }
}
